name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      run: |
        npm install -g npm@7
        npm ci
      working-directory: ./api
    - name: Build source code
      run: npm run build --if-present
      working-directory: ./api
    # - name: Run tests
    #   run: npm test
    #   working-directory: ./api
